---
name: SQL-ReservedWords-MySQL
version: 0.2
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Reserved SQL words by MySQL
license: perl
requires:
  Sub::Exporter: 0
build_requires:
  Test::More: 0
provides:
  SQL::ReservedWords::MySQL:
    file: lib/SQL/ReservedWords/MySQL.pm
    version: 0.2
generated_by: Module::Build version 0.2611
